"""Publish metadata and figure copies without touching the original seven papers."""
from pathlib import Path
import json,shutil
HERE=Path(__file__).resolve().parent;ROOT=HERE.parents[2]
items=json.loads((HERE/'editorial.json').read_text())
pub={x['id']:x for x in json.loads((HERE/'publication-manifest.json').read_text())}
charts={x['id']:x for x in json.loads((HERE/'chart-contracts.json').read_text())}
for item in items:
    p=pub[item['id']];c=charts[item['figure']]
    item.update(pages=p['pages'],figures=p['figures'],figureTitle=c['title'],figureScope=c['scope'],reading=c['reading'],alt=c['title']+'. '+c['scope'],width=c['width'],height=c['height'])
    shutil.copyfile(HERE/'figures'/f"{item['figure']}.png",ROOT/'assets/insights'/f"{item['figure']}.png")
target=ROOT/'src/data/research-extensions.js'
target.write_text('// Generated by argument-structure-studies-2026-10-09/sync_site.py.\nexport const researchExtensions = '+json.dumps(items,indent=2,ensure_ascii=False)+';\n')
print('Published three research entries and three site figures')
