"""Publish the reviewed edition, never silently recompute editorial conclusions."""
import json,re,shutil
from pathlib import Path
from PIL import Image
HERE=Path(__file__).resolve().parent;ROOT=HERE.parents[2]
R=json.loads((HERE/'results.json').read_text())
CHARTS={x['id']:x for x in json.loads((HERE/'chart-contracts.json').read_text())}
PUB=json.loads((HERE/'publication-manifest.json').read_text())
def expand(match):
    value=R
    for k in match[1].split('.'):value=value[k] if isinstance(value,dict) else value[int(k)]
    return f'{value:,.{match[2]}f}' if match[2] else str(value)
raw=(HERE/'editorial.json').read_text()
items=json.loads(re.sub(r'\{\{([\w.]+)(?::(\d+))?\}\}',expand,raw))
for item,pub in zip(items,PUB):
    assert item['pdf']==pub['file']
    figure=CHARTS[item['figure']]
    image=HERE/'figures'/f'{item["figure"]}.png'
    item.update(width=Image.open(image).width,height=Image.open(image).height,
        figureTitle=figure['title'],figureScope=figure['scope'],reading=figure['reading_key'],
        alt=figure['title']+'. '+item['explanation'],pages=pub['pages'],figures=pub['figures'],
        version='20261009-corpus308-stability' if item['id']=='ranking-confidence' else '20261009-corpus308')
    shutil.copyfile(image,ROOT/'assets/insights'/image.name)
snapshot=dict(date=R['edition'],isoDate='2026-10-09',version='20261009-corpus308-stability',
    sourceCommit=R['source_commit'],counts=R['counts'],newAssessments=R['derived']['new_assessments'],
    decisive=R['p5']['decisive'],ties=R['p5']['ties'],ranked=R['p7']['ranked_speakers'],appearances=R['p7']['eligible_appearances'],
    directory='/docs/analysis/corpus-papers-2026-10-09/')
output='// Generated by the reviewed October research edition. Do not hand-edit.\n'
output+='export const researchEdition = '+json.dumps(snapshot,indent=2,ensure_ascii=False)+';\n'
output+='export const researchInsights = '+json.dumps(items,indent=2,ensure_ascii=False)+';\n'
(ROOT/'src/data/research-edition.js').write_text(output)
print('Updated shared website research data and seven displayed figures.')
