#!/usr/bin/env node

import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { DIMENSION_WEIGHTS, scoreDimensions } from "./lib/reassessment-scoring.mjs";

const [passArgument, inventoryArgument, lockArgument, gateArgument] = process.argv.slice(2);
if (!passArgument || !inventoryArgument || !lockArgument || !gateArgument) { console.error("Usage: node scripts/validate-scoring-pass-v2.3.mjs <pass.json> <inventory.json> <response-lock.json> <gate.json>"); process.exit(1); }
const workspaceRoot = path.resolve(".");
const passPath = path.resolve(passArgument); const inventoryPath = path.resolve(inventoryArgument); const lockPath = path.resolve(lockArgument); const gatePath = path.resolve(gateArgument);
const workflowPath = path.join(workspaceRoot, "docs", "assessment-workflow-v2.3.md"); const rubricPath = path.join(workspaceRoot, "docs", "reassessment-rubric-v2.3.md"); const schemaPath = path.join(workspaceRoot, "docs", "calibration", "v2.3", "scoring-pass-schema.json");
function assert(condition, message) { if (!condition) throw new Error(message); }
function sha256(source) { return createHash("sha256").update(source).digest("hex"); }
function relative(filePath) { return path.relative(workspaceRoot, filePath).split(path.sep).join("/"); }
function exactKeys(value, expected, label) { assert(value && typeof value === "object" && !Array.isArray(value), `${label} must be an object`); assert(JSON.stringify(Object.keys(value).sort()) === JSON.stringify([...expected].sort()), `${label} keys differ from the exact v2.3 contract`); }
function integer(value, label, min, max) { assert(Number.isInteger(value) && value >= min && value <= max, `${label} must be an integer from ${min} to ${max}`); }
function digest(value, label) { assert(typeof value === "string" && /^[a-f0-9]{64}$/.test(value), `${label} must be a SHA-256 digest`); }
function validateAdjustment(entry, label, moveIds, burdenIds) {
  exactKeys(entry, ["value", "rationale", "eligibility"], label); integer(entry.value, `${label}.value`, -5, 5); assert(typeof entry.rationale === "string" && entry.rationale.trim().length >= 20, `${label}.rationale too short`);
  const e = entry.eligibility; exactKeys(e, ["distinctDebateWideConsequence", "affectsBurdenCompletion", "notAlreadyScored", "affectedBurdenIds", "completionCriterion", "relatedMoveIds", "distinctConsequence", "alreadyCapturedBy", "counterfactual"], `${label}.eligibility`);
  for (const key of ["distinctDebateWideConsequence", "affectsBurdenCompletion", "notAlreadyScored"]) assert(typeof e[key] === "boolean", `${label}.eligibility.${key} must be boolean`);
  for (const key of ["affectedBurdenIds", "relatedMoveIds", "alreadyCapturedBy"]) assert(Array.isArray(e[key]) && new Set(e[key]).size === e[key].length, `${label}.eligibility.${key} must be a unique array`);
  for (const id of e.affectedBurdenIds) assert(burdenIds.has(id), `${label} references unknown burden ${id}`); for (const id of e.relatedMoveIds) assert(moveIds.has(id), `${label} references unknown move ${id}`);
  for (const key of ["completionCriterion", "distinctConsequence", "counterfactual"]) assert(typeof e[key] === "string" && e[key].trim(), `${label}.eligibility.${key} is required`);
  const eligible = e.distinctDebateWideConsequence && e.affectsBurdenCompletion && e.notAlreadyScored && e.affectedBurdenIds.length > 0 && e.completionCriterion.trim().toLowerCase() !== "none" && e.relatedMoveIds.length > 0 && e.distinctConsequence.trim().toLowerCase() !== "none" && e.alreadyCapturedBy.length === 0 && e.counterfactual.trim().toLowerCase() !== "none";
  assert(entry.value === 0 ? !eligible : eligible, `${label} conflicts with strengthened burden-exclusion rule`);
}

const [passSource, inventorySource, lockSource, gateSource, workflowSource, rubricSource, schemaSource] = await Promise.all([readFile(passPath, "utf8"), readFile(inventoryPath, "utf8"), readFile(lockPath, "utf8"), readFile(gatePath, "utf8"), readFile(workflowPath, "utf8"), readFile(rubricPath, "utf8"), readFile(schemaPath, "utf8")]);
const scoringPass = JSON.parse(passSource); const inventory = JSON.parse(inventorySource); const lock = JSON.parse(lockSource); const gate = JSON.parse(gateSource);
exactKeys(scoringPass, ["schemaVersion", "workflowVersion", "rubricVersion", "gateId", "debateId", "debateNumber", "pass", "assessmentModel", "calibrationOnly", "completedAt", "isolation", "source", "dimensionWeights", "moveScores", "sectionScores", "burdenCompletionAdjustment", "overall", "calculationAudit"], "pass");
assert(scoringPass.schemaVersion === "2.3-scoring-pass" && scoringPass.workflowVersion === gate.workflowVersion && scoringPass.rubricVersion === gate.rubricVersion && scoringPass.gateId === gate.gateId, "scoring pass version mismatch");
assert(scoringPass.debateId === inventory.debateId && scoringPass.debateId === lock.debateId && scoringPass.debateNumber === inventory.debateNumber, "scoring pass identity mismatch");
assert(["A", "B"].includes(scoringPass.pass) && scoringPass.assessmentModel === "5.6 Sol" && scoringPass.calibrationOnly === true && !Number.isNaN(Date.parse(scoringPass.completedAt)), "scoring pass metadata mismatch");
exactKeys(scoringPass.isolation, ["method", "allowedInputs", "prohibitedInputsConfirmed", "contaminationDetected", "statement"], "isolation"); assert(scoringPass.isolation.method === "fresh-isolated-scoring-task" && scoringPass.isolation.prohibitedInputsConfirmed === true && scoringPass.isolation.contaminationDetected === false && scoringPass.isolation.statement.trim().length >= 40, "scoring isolation failed");
exactKeys(scoringPass.source, ["videoId", "inventoryPath", "inventorySha256", "responseLockPath", "responseLockSha256", "transcriptSha256", "eventsSha256", "captionManifestSha256", "audioVerificationPath", "audioVerificationSha256", "gateManifestSha256", "workflowSha256", "rubricSha256", "schemaSha256", "limitations"], "source");
for (const key of ["inventorySha256", "responseLockSha256", "transcriptSha256", "eventsSha256", "captionManifestSha256", "audioVerificationSha256", "gateManifestSha256", "workflowSha256", "rubricSha256", "schemaSha256"]) digest(scoringPass.source[key], `source.${key}`);
assert(scoringPass.source.inventoryPath === relative(inventoryPath) && scoringPass.source.inventorySha256 === sha256(inventorySource), "inventory source mismatch"); assert(scoringPass.source.responseLockPath === relative(lockPath) && scoringPass.source.responseLockSha256 === sha256(lockSource), "response lock source mismatch"); assert(scoringPass.source.gateManifestSha256 === sha256(gateSource) && scoringPass.source.workflowSha256 === sha256(workflowSource) && scoringPass.source.rubricSha256 === sha256(rubricSource) && scoringPass.source.schemaSha256 === sha256(schemaSource), "workflow contract hash mismatch");
const gateDebate = gate.sample.debates.find((entry) => entry.debateId === inventory.debateId); assert(gateDebate && scoringPass.source.videoId === gateDebate.videoId, "videoId mismatch"); const captionRoot = path.join(workspaceRoot, ".assessment-cache", "captions", gateDebate.videoId); const audioPath = path.resolve(scoringPass.source.audioVerificationPath);
const [transcriptSource, eventsSource, captionManifestSource, audioSource] = await Promise.all([readFile(path.join(captionRoot, "transcript.txt")), readFile(path.join(captionRoot, "events.json")), readFile(path.join(captionRoot, "manifest.json")), readFile(audioPath)]);
for (const [label, actual, source] of [["transcript", scoringPass.source.transcriptSha256, transcriptSource], ["events", scoringPass.source.eventsSha256, eventsSource], ["captionManifest", scoringPass.source.captionManifestSha256, captionManifestSource], ["audioVerification", scoringPass.source.audioVerificationSha256, audioSource]]) assert(actual === sha256(source), `${label} hash mismatch`);
const expectedAllowlist = [relative(workflowPath), relative(rubricPath), relative(schemaPath), relative(gatePath), relative(inventoryPath), relative(lockPath), relative(audioPath), relative(path.join(captionRoot, "transcript.txt")), relative(path.join(captionRoot, "events.json")), relative(path.join(captionRoot, "manifest.json"))].sort(); assert(JSON.stringify([...scoringPass.isolation.allowedInputs].sort()) === JSON.stringify(expectedAllowlist), "isolation.allowedInputs must equal exhaustive scoring allowlist");
exactKeys(scoringPass.dimensionWeights, Object.keys(DIMENSION_WEIGHTS), "dimensionWeights"); for (const [key, value] of Object.entries(DIMENSION_WEIGHTS)) assert(scoringPass.dimensionWeights[key] === value, `dimension weight ${key} mismatch`);

const inventoryEntries = inventory.sections.flatMap((section) => section.moves.map((move) => ({section, move}))); const inventoryById = new Map(inventoryEntries.map((entry) => [entry.move.id, entry])); const lockById = new Map(lock.classifications.map((item) => [item.moveId, item])); const moveIds = new Set(inventoryById.keys()); const burdenIds = new Set(inventory.burdens.map((burden) => burden.id));
assert(scoringPass.moveScores.length === inventoryEntries.length, "every inventory move must be scored once"); const passById = new Map(); const ranges = {"full-answer": [80,100], "partial-answer": [55,79], "diagnostic-defeat": [80,100], "relevant-counterargument": [50,69], "justified-reframe": [80,100], "weaker-substitution": [0,49], "constructive-opening": [0,100]};
for (const [index, item] of scoringPass.moveScores.entries()) {
  const label = `moveScores[${index}]`; exactKeys(item, ["moveId", "sectionId", "side", "importance", "timestamp", "sourceSpan", "lockedResponseClass", "calibrationCharitySubratings", "dimensions", "moveScore", "evidenceBasis", "rationale", "assessmentConfidence"], label);
  assert(!passById.has(item.moveId), `${label}.moveId duplicated`); const inv = inventoryById.get(item.moveId); const responseLock = lockById.get(item.moveId); assert(inv && responseLock, `${label}.moveId unknown`);
  assert(item.sectionId === inv.section.id && item.side === inv.move.side && item.importance === inv.move.importance && item.timestamp === inv.move.timestamp && JSON.stringify(item.sourceSpan) === JSON.stringify(inv.move.sourceSpan), `${label} changed locked inventory data`);
  assert(item.lockedResponseClass === responseLock.responseClass, `${label} changed locked response class`);
  exactKeys(item.calibrationCharitySubratings, ["epistemicCalibration", "representationalCharity", "combined"], `${label}.calibrationCharitySubratings`); for (const [key, value] of Object.entries(item.calibrationCharitySubratings)) integer(value, `${label}.calibrationCharitySubratings.${key}`, 0, 100); const combined = Math.round((item.calibrationCharitySubratings.epistemicCalibration + item.calibrationCharitySubratings.representationalCharity) / 2); assert(item.calibrationCharitySubratings.combined === combined, `${label} calibration/charity combined mismatch`);
  exactKeys(item.dimensions, Object.keys(DIMENSION_WEIGHTS), `${label}.dimensions`); for (const [key, value] of Object.entries(item.dimensions)) integer(value, `${label}.dimensions.${key}`, 0, 100); assert(item.dimensions.calibrationCharity === combined, `${label}.dimensions.calibrationCharity mismatch`);
  const [minimum, maximum] = ranges[item.lockedResponseClass] ?? []; assert(minimum !== undefined && item.dimensions.responsiveness >= minimum && item.dimensions.responsiveness <= maximum, `${label} responsiveness violates locked ${item.lockedResponseClass} range ${minimum}-${maximum}`);
  assert(item.moveScore === scoreDimensions(item.dimensions, `${label}.dimensions`), `${label}.moveScore mismatch`); assert(item.evidenceBasis.trim().length >= 20 && item.rationale.trim().length >= 40 && ["high", "medium", "low"].includes(item.assessmentConfidence), `${label} rationale or confidence invalid`); passById.set(item.moveId, item);
}
assert(scoringPass.sectionScores.length === inventory.sections.length, "section count mismatch"); let weightTotal = 0;
for (const [index, invSection] of inventory.sections.entries()) { const section = scoringPass.sectionScores[index]; const label = `sectionScores[${index}]`; exactKeys(section, ["sectionId", "weightPercent", "pro", "con"], label); assert(section.sectionId === invSection.id && section.weightPercent === invSection.weight, `${label} identity mismatch`); weightTotal += section.weightPercent;
  for (const side of ["pro", "con"]) { exactKeys(section[side], ["moveIds", "importanceTotal", "score"], `${label}.${side}`); const moves = invSection.moves.filter((move) => move.side === side); const ids = moves.map((move) => move.id); assert(JSON.stringify(section[side].moveIds) === JSON.stringify(ids), `${label}.${side}.moveIds mismatch`); const importanceTotal = moves.reduce((sum, move) => sum + move.importance, 0); assert(section[side].importanceTotal === importanceTotal, `${label}.${side}.importanceTotal mismatch`); const expected = Math.round(moves.reduce((sum, move) => sum + passById.get(move.id).moveScore * move.importance, 0) / importanceTotal); assert(section[side].score === expected, `${label}.${side}.score mismatch`); }
}
assert(weightTotal === 100, "section weights must total 100"); exactKeys(scoringPass.burdenCompletionAdjustment, ["pro", "con"], "burdenCompletionAdjustment"); exactKeys(scoringPass.overall, ["pro", "con"], "overall");
for (const side of ["pro", "con"]) { validateAdjustment(scoringPass.burdenCompletionAdjustment[side], `burdenCompletionAdjustment.${side}`, moveIds, burdenIds); exactKeys(scoringPass.overall[side], ["weightedSectionMean", "burdenCompletionAdjustment", "score"], `overall.${side}`); const weighted = Number(scoringPass.sectionScores.reduce((sum, section) => sum + section[side].score * section.weightPercent / 100, 0).toFixed(2)); assert(scoringPass.overall[side].weightedSectionMean === weighted && scoringPass.overall[side].burdenCompletionAdjustment === scoringPass.burdenCompletionAdjustment[side].value && scoringPass.overall[side].score === Math.max(0, Math.min(100, Math.round(weighted + scoringPass.burdenCompletionAdjustment[side].value))), `overall.${side} mismatch`); }
exactKeys(scoringPass.calculationAudit, ["moveCount", "sectionCount", "sectionWeightTotal", "allLockedClassesUsed", "allCalibrationCharityMeansRecomputed", "allMoveScoresRecomputed", "allSectionScoresRecomputed", "allOverallScoresRecomputed"], "calculationAudit"); assert(scoringPass.calculationAudit.moveCount === inventoryEntries.length && scoringPass.calculationAudit.sectionCount === inventory.sections.length && scoringPass.calculationAudit.sectionWeightTotal === 100, "calculation audit counts mismatch"); for (const key of ["allLockedClassesUsed", "allCalibrationCharityMeansRecomputed", "allMoveScoresRecomputed", "allSectionScoresRecomputed", "allOverallScoresRecomputed"]) assert(scoringPass.calculationAudit[key] === true, `calculationAudit.${key} must be true`);
console.log(JSON.stringify({status: "passed", debateId: scoringPass.debateId, pass: scoringPass.pass, moves: inventoryEntries.length, sections: inventory.sections.length, lockedClasses: "verified", calibrationCharityMeans: "verified", schemaUniformity: "exact-v2.3-scoring-contract", passSha256: sha256(passSource)}, null, 2));
